### PR TITLE
Update en-bulletin.md

### PR DESCRIPTION
**Pull request by cosola**
@misscs 

* Please review the revisions to the English content for the bulletin and comments. 

* I have the acknowledgments and comments ready for review.

Thanks a lot.

### CODE REVIEW

**Comment by misscs** [comment]
@cosola I'm fine with these changes. I'd like to merge it with the grammatical issues resolved. Please take the first pass at editing the content. I think Grammarly will catch most of the errors I'm seeing. 

Let me know when you're done and I'll take the final pass. Thanks!

**Review by misscs — CHANGES_REQUESTED** [review]
Rejecting until it's run through grammarly. I don't want to duplicate work.

**Review by misscs — APPROVED** [review]
Much better. More dynamic and interesting. Will make a few corrections on the main PR.

**Comment by cosola** [comment]
Thanks. Is content ready for translation now?

**Pull request merged**
